### ISSUE TITLE
Adicionar aba Atividades na página de gestão de usuários

### ISSUE THREAD

**Issue by cesardelucca** [mapasculturais/plugin-MapasBlame#2]
A aba deverá listar as atividades dos usuários e conter filtros para consulta.

**Comment by daphnemartinsba** [comment]
Ao invés da aba Atividades, foi criada a aba Log de acessos, essa aba lista as atividades dos usuários na coluna action e os filtros são aplicados conforme as actions possíveis, é possível filtrar as actions por data. 
Requisito funcional não especificado na regra de negócio: O filtro de data não funciona sem action.
